[project]
name = "mlops-bootcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.0.1",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
