aliases:
  challenger: '1'
  champion: '2'
creation_timestamp: 1762252958839
deployment_job_id: null
deployment_job_state: null
description: ''
last_updated_timestamp: 1762259286557
name: tracking-quickstart
